import type { IncomingMessage, ServerResponse } from 'node:http';
// Import the PRE-BUNDLED backend (generated by scripts/bundle-backend.mjs into
// api/_backend.mjs, which is `_`-prefixed so Vercel does not treat it as a route). The
// bundle inlines the entire server/src graph, so there is no cross-directory runtime
// module resolution for Vercel to get wrong. The `.mjs` specifier is explicit (required
// by Node's ESM resolver).
import { buildApp } from './_backend.mjs';

type NodeHandler = (req: IncomingMessage, res: ServerResponse) => void;

let app: NodeHandler | undefined;
let bootError: Error | undefined;

try {
    app = buildApp();
} catch (error) {
    bootError = error instanceof Error ? error : new Error(String(error));
}

export default function handler(req: IncomingMessage, res: ServerResponse): void {
    if (bootError) {
        res.statusCode = 500;
        res.setHeader('content-type', 'application/json');
        res.end(
            JSON.stringify({
                error: { code: 'backend_boot_error', message: bootError.message },
                stack: process.env.VERCEL_ENV === 'production' ? undefined : bootError.stack,
            }),
        );
        return;
    }
    app!(req, res);
}
