import * as http from 'node:http';
// Single Vercel serverless entry for the whole backend. vercel.json rewrites every
// `/api/*` request to this function (`/api/(.*)` -> `/api`); the original request path is
// preserved in `req.url`, so the Express app routes on `/api/health`, `/api/auth/*`, etc.
// This avoids relying on Vercel's dynamic-route filename parsing (a `[[...path]]` optional
// catch-all is Next-only and was mis-parsed as a single segment here).
//
// Import the PRE-BUNDLED backend (generated by scripts/bundle-backend.mjs into
// api/_backend.mjs, which is `_`-prefixed so Vercel does not treat it as a route). The
// bundle inlines the entire server/src graph, so there is no cross-directory runtime
// module resolution for Vercel to get wrong. The `.mjs` specifier is explicit (required
// by Node's ESM resolver).
//
// The default export is an http.Server (not a bare req/res handler) — feature 019's
// retrospective board WebSocket channel (GET /api/retrospectives/:id/live) requires
// access to the server's 'upgrade' event, which only an http.Server exposes. This is
// Vercel's own documented pattern for Node.js Function WebSockets (research.md §1).
import { buildApp } from './_backend.mjs';

let server: http.Server;

try {
    server = buildApp();
} catch (error) {
    const bootError = error instanceof Error ? error : new Error(String(error));
    server = http.createServer((_req, res) => {
        res.statusCode = 500;
        res.setHeader('content-type', 'application/json');
        res.end(
            JSON.stringify({
                error: { code: 'backend_boot_error', message: bootError.message },
                stack: process.env.VERCEL_ENV === 'production' ? undefined : bootError.stack,
            }),
        );
    });
}

export default server;
